### PR TITLE
Minima PPM receiver fixup

### PR DESCRIPTION
**Pull request by FenomPL**
There is no reasonable explanation why it should be considered as a "decoder reset". Without this fixup Minima clone will not work in PPM mode... I'm not sure but probably it sends additional chanell with RSSI information... just guessing. Confirmed to work properly without this part of code.

### CODE REVIEW

**Comment by SirAlex** [comment]
This check used to detect bad situations, when we skipped one of SYNC signal.
I'm think, you must change  AVR_RC_INPUT_NUM_CHANNELS to your channel count. But this patch will also work of course.

**Comment by FenomPL** [comment]
I don't agree with you. The channel number for this particular case is 8. That is what Minima receiver state as a channels number. Any correct signal above 8th channel currently is resetting decoder and it makes the system unusable. PPM definition does not define how many channels are sent in it... The simplest solution is to ignore all !correct! signals above AVR_RC_INPUT_NUM_CHANNELS and definitely it will not cause skipping SYNC signal...

**Comment by SirAlex** [comment]
AVR_RC_INPUT_NUM_CHANNELS it's not your RX channel count, it's cannel count in PPM SUM signal.
If your receiver send 8 regular channel + RSSI channel, you must configure it to 9 channels.

**Comment by SirAlex** [comment]
But, yes. Early I have idea to make some kind of channel count auto-detecting... But there is more important troubles than this.

**Comment by FenomPL** [comment]
The problem is that there is no valid documentation about PPM in Minima... my problem was that it was simply not working. I doubt regular users will change anything more than simple configuration settings to make it work. It has to be user proof :)

**Comment by secretman28** [comment]
i willl try my ppmsum tomorow, i try so hard to make this work lol and get back to normal 8 ugly wire setup... 
will post result as soon as possible

**Comment by Paku-** [comment]
Hi guys,

The original idea here, as I remember - it was months or a year ago - was to reset the decoder state machine in case it lost PPM_SUM signal logic, what is - we can not get more channels then defined (expected). If we have got - it means a kind of failure. I do not know Minima you are talking about here and the RSSI signal issue with it. But if the poor CPPM signal consists of more then 8 channels (like RSSI sent as 9th channel (??)) you have to define the Rx as 9 channel model and read this RSSI as standard channel. you may then discard that value but to make the decoder working safely it has to know the original signal is 9ch not 8ch.

You may remove this part of code but you are loosing important safety check ...
It would be better to make it working as 9ch Rx.

Edit:
One more important factor, I would check if the memory cell just after channels table is not overwritten now .... table size is 8 while you read 9th channel :)

**Pull request closed without merging**
