### PR TITLE
Copter: bugfix for starting in LOITER

### PR DESCRIPTION
**Pull request by DerFlash**
Loiter's Roll-Pitch mode was not being set on start-up.

### CODE REVIEW

**Comment by smurfy** [comment]
never mind my old comment i'm stupid ^^:D

what was the original commit hash from upstream?

**Comment by DerFlash** [comment]
Right. This is pulled from the original upstream. ;-)

Hash for this commit is either:
e15527973a42fc64c17a7c556f206a9362aceee8 (ArduCopter-3.1 branch)
or
99f851fc87dc45698ae27b61a8bd3ea1becbb871 (master)

**Comment by smurfy** [comment]
Ok thank you, so the fix got live with upstream 3.1.1. 

Not sure what @SirAlex plans are but i guess, after he finishes the 3.1.x port he tries to get the latest 3.1.x version ported. so at the moment that would be 3.1.2. (based on upstream branching/tags)

I also again noticed that the upstream guys don't tag every release and that could be a bit confusing ^^ i think thats a bit offtopic and i will raise an issue upstream.

**Comment by DerFlash** [comment]
Thanks for the info.

I tried to find out on what version the 3.1 MPNG beta was based on and saw this small change on the way to 3.1.1. The 3.1.2 changes were a bit heavier and would need much more time to port (since @SirAlex noted that he needs to do that from scratch with every release).

So I thought after fixing this small issue on my fork I should throw you a PR for the beta branch here (which would do no harm and just fix a small issue), in case some more people are already using it.

**Comment by smurfy** [comment]
> So I thought after fixing this small issue on my fork I should throw you a PR for the beta branch here (which would do no harm and just fix a small issue), in case some more people are already using it.

That was a really good idea :)

> I tried to find out on what version the 3.1 MPNG beta was based on and saw this small change on the way to 3.1.1. The 3.1.2 changes were a bit heavier and would need much more time to port (since @SirAlex noted that he needs to do that from scratch with every release).

I'm not 100% familiar with the process of @SirAlex and not really skilled in arduino development. there are different things which changes between the releases. 
- HAL changes of the upstream releases
- Copter, Plane, Rover specific changes
- Supporting changes like moving code parts from for example Copter to a standalone library to get reused by Plane. (Last thing i noticed was the BatteryMonitor)
- Small interface changes of util classes (DataStorage changed recently)

So in our example what did change between 3.1.0 and 3.1.2 (based on the releasenotes.txt)
- Mainly Pixhawk HAL (should not affect us)
- Small Copter fixes (like the one this PR is about)
- Possible some interface changes hopefully not many. (not in the release-notes)

So i think even an update to 3.1.2 should be possible quite easy.

**Comment by wengwah** [comment]
Waiting anxiously for 3.1. Looking forward for the drift and sport mode of flying.

**Comment by DerFlash** [comment]
@SirAlex Still waiting. APM code now has log downloading without using terminal connection and much more. How's the actual progress?

**Pull request closed without merging**
